pipeline {
    agent any

    options {
        timeout(time: 10, unit: 'MINUTES')
    }

    parameters {
        string(name: 'GITHUB_CREDENTIAL', defaultValue: 'github_cred', description: 'Github access credentials id')
        string(name: 'GITHUB_REPO_URL', defaultValue: 'https://github.com/ogob31/magvector_project.git', description: 'Github repository url')
        string(name: 'GITHUB_BRANCH', defaultValue: 'main', description: 'Github branch for your build')
        choice(name: 'TERRAFORM_ACTION', choices: ['apply', 'destroy'], description: 'Select Terraform action: Apply or Destroy')
    }

    environment {
        AWS_REGION = 'us-east-1'
    }

    stages {
        stage("Validate Parameters") {
            steps {
                script {
                    if (!params.TERRAFORM_ACTION?.trim()) {
                        error('TERRAFORM_ACTION is required. Please choose either "apply" or "destroy".')
                    }
                }
            }
        }

        stage("Checkout Code From GitHub") {
            steps {
                git branch: "${params.GITHUB_BRANCH}",
                    credentialsId: "${params.GITHUB_CREDENTIAL}",
                    url: "${params.GITHUB_REPO_URL}"
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh '''
                      set -e
                      terraform --version
                      terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh '''
                      set -e
                      terraform plan
                    '''
                }
            }
        }

        stage('Terraform Apply Or Destroy') {
            steps {
                dir('terraform') {
                    sh """
                      set -e
                      terraform ${params.TERRAFORM_ACTION} -auto-approve
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
