pipeline {
    agent any
    parameters {
        string(name: 'GITHUB_CREDENTIAL', defaultValue: 'github_creds', description: 'Github access credentials id')
        string(name: 'GITHUB_BRANCH', defaultValue: 'main', description: 'Branch to build from')
        string(name: 'GITHUB_REPO_URL', defaultValue: 'https://github.com/essiendaniel33/marketvector.git', description: 'Repository URL to build from')
        string(name: 'VERSION', defaultValue: "V00${BUILD_ID}", description: 'Version of Docker image to be built, e.g., V001')
    }

    environment {
        GITHUB_CREDENTIAL = "${params.GITHUB_CREDENTIAL}"
        GITHUB_BRANCH = "${params.GITHUB_BRANCH}"
        GITHUB_REPO_URL = "${params.GITHUB_REPO_URL}"
        VERSION = "${params.VERSION}"
        KUBECONFIG = '/home/jenkins/.kube/config'
        ECR_REPO_URL = "905418280053.dkr.ecr.us-east-1.amazonaws.com/eks-repo"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Clone GitHub Repo') {
            steps {
                git branch: "${GITHUB_BRANCH}", credentialsId: "${GITHUB_CREDENTIAL}", url: "${GITHUB_REPO_URL}"
            }
        }

        stage('Building Docker Image') {
            steps {
                sh "docker build -t eks-repo ."
            }
        }

        stage('Push To Elastic Container Registry') {
            steps {
                script {
                    sh """
                        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REPO_URL}
                        docker tag eks-repo:latest ${ECR_REPO_URL}:${VERSION}
                        docker push ${ECR_REPO_URL}:${VERSION}
                    """
                }
            }
        }

        stage('Update Kubernetes Deployment') {
            steps {
                script {
                    dir('Kubernetes') {
                        sh """
                            echo "Updating deployment.yaml with the new image version"
                            sed -i 's|image:.*|image: ${ECR_REPO_URL}:${VERSION}|g' deployment.yaml
                            cat deployment.yaml # Display the updated file for verification
                        """
                    }
                }
            }
        }

        stage('Deploy To K8S Cluster') {
            steps {
                script {
                    dir('Kubernetes') {
                        sh """
                            echo "Deploying to Kubernetes cluster"
                            export KUBECONFIG=${KUBECONFIG}
                            kubectl apply -f .
                            sleep 30
                        """
                    }
                }
            }
        }
        
        stage('Get K8S Cluster Services') {
            steps {
                script {
                    dir('Kubernetes') {
                        sh """
                            echo "Fetching Kubernetes cluster services"
                            export KUBECONFIG=${KUBECONFIG}
                            kubectl get svc --namespace=mv-app-dev
                        """
                    }
                }
            }
        }
        
        stage('Commit and Push Updated YAML') {
            steps {
                script {
                    
                        sh """
                            git config user.name "Jenkins CI"
                            git config user.email "jenkins@ci.com"

                            git add --all
                            git commit -m "Update deployment.yaml with image version ${VERSION}"
                        """
                        withCredentials([usernamePassword(credentialsId: GITHUB_CREDENTIAL, passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                            sh """
                                git push https://${GIT_USERNAME}:${GIT_PASSWORD}@${GITHUB_REPO_URL.replace("https://", "")} ${GITHUB_BRANCH}
                            """
                        }
                    
                }
            }
        }
    }
}
